trigger:
  - "*"

pool:
  vmImage: "ubuntu-latest"

variables:
  projectName: "Remoteit"
  buildConfiguration: "Release"
  major: 0
  minor: 1
  patch: $[counter(variables['minor'], 0)] #this will reset when we bump minor
  NugetVersion: $(major).$(minor).$(patch)

jobs:
  - job: Build_and_Test
    steps:
      - task: DotNetCoreCLI@2
        name: "Restore Solution"
        inputs:
          command: "restore"
          feedsToUse: "select"
      - task: DotNetCoreCLI@2
        name: "Build Solution"
        inputs:
          command: "build"
      - task: DotNetCoreCLI@2
        name: "Run_Unit_Tests"
        inputs:
          command: "test"

  - job: NuGet
    dependsOn: Build_and_Test
    steps:
      - task: DotNetCoreCLI@2
        name: "Build Remoteit Class Library"
        inputs:
          command: "build"
          projects: "./$(projectName)/$(projectName).csproj"
          arguments: "--configuration $(buildConfiguration)"
      - task: NuGetCommand@2
        name: "Pack NuGet Package"
        inputs:
          command: "pack"
          packagesToPack: "./$(projectName)/$(projectName).csproj"
          versioningScheme: "byEnvVar"
          versionEnvVar: "NugetVersion"
          configuration: "$(buildConfiguration)"
