trigger:
- "*"

pool:
  vmImage: 'ubuntu-latest'

variables:
  projectName: 'Remoteit'
  buildConfiguration: 'Release'
  major: 0
  minor: 1
  patch: $[counter(variables['minor'], 0)] #this will reset when we bump minor
  NugetVersion: $(major).$(minor).$(patch)

jobs:
- job: Build_and_Test
  steps:
    - task: DotNetCoreCLI@2
      name: 'Restore_Solution'
      inputs:
        command: 'restore'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      name: 'Build_Solution'
      inputs:
        command: 'build'
    - task: DotNetCoreCLI@2
      name: 'Run_Unit_Tests'
      inputs:
        command: 'test'

- job: Publish_Package
  dependsOn: Build_and_Test
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: './$(projectName)/$(projectName).csproj'
      configuration: 'Release'
  - task: NuGetCommand@2
    inputs:
      command: 'pack'
      packagesToPack: './$(projectName)/$(projectName).csproj'
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'NugetVersion'
      configuration: 'Release'
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'Personal NuGet'
  